name: calendar_date_picker2
description: Highly customisable calendar picker built on Flutter's original CalendarDatePicker
version: 0.0.4
homepage: https://github.com/theideasaler/calendar_date_picker2

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: